# 应用名称
spring:
  application:
    name: redis-lazy
  redis:
    database: 0
    port: 6579
    host: 127.0.0.1
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
    expire: 21600

