GET http://localhost:53010/uaa/oauth/authorize?client_id=c1&response_type=token&scope=ROLE_API ROLE_ADMIN&redirect_uri=http://www.baidu.com
Accept: */*
Cache-Control: no-cache

###
POST http://localhost:53020/uaa/oauth/token?client_id=c1&client_secret=123&grant_type=authorization_code&code=CQA78X&redirect_uri=http://www.baidu.com

Accept: */*
Cache-Control: no-cache

###
GET http://localhost:53010/order/r1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSJdLCJ1c2VyX25hbWUiOiJ7XCJmdWxsbmFtZVwiOlwi5byg5LiJXCIsXCJpZFwiOlwiMVwiLFwibW9iaWxlXCI6XCIxXCIsXCJwYXNzd29yZFwiOlwiJDJhJDEwJGFGc09GenVqdFBDblVDVUtjb3pzSHV4MHJRLzNmYUFIR0ZTVmI5WS5CMW50cG1FaGpSdHJ1XCIsXCJ1c2VybmFtZVwiOlwiemhhbmdzYW5cIn0iLCJzY29wZSI6WyJST0xFX0FQSSIsIlJPTEVfQURNSU4iXSwiZXhwIjoxNjA2NjQyNjUxLCJhdXRob3JpdGllcyI6WyJwMSIsInAzIl0sImp0aSI6ImRmMGI2NWY5LWZkOTktNGFmYS05NjYxLTUzMDcyNTQyMTM0ZCIsImNsaWVudF9pZCI6ImMxIn0.p_PNaDsQpO4mpcYNpx52CA0D-2h9HXIP478TVSvOF_4

###
POST http://localhost:53010/uaa/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsicmVzMSJdLCJ1c2VyX25hbWUiOiJ7XCJmdWxsbmFtZVwiOlwi5byg5LiJXCIsXCJpZFwiOlwiMVwiLFwibW9iaWxlXCI6XCIxXCIsXCJwYXNzd29yZFwiOlwiJDJhJDEwJGFGc09GenVqdFBDblVDVUtjb3pzSHV4MHJRLzNmYUFIR0ZTVmI5WS5CMW50cG1FaGpSdHJ1XCIsXCJ1c2VybmFtZVwiOlwiemhhbmdzYW5cIn0iLCJzY29wZSI6WyJST0xFX0FQSSJdLCJleHAiOjE2MDY2NDI1MjAsImF1dGhvcml0aWVzIjpbInAxIiwicDMiXSwianRpIjoiZjI3OGY0YWMtYzFmNy00NGFkLTk0ODctNTc4YTUwMWZmZTYyIiwiY2xpZW50X2lkIjoiYzEifQ.S-2vcywkiGGbC5HGnM1WZYOmZR41W0bR5db7Mc8V7NY

